spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/scorpio_member?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: leslie
    type: com.alibaba.druid.pool.DruidDataSource
  profiles:
    active: cache  # 激活cache配置
  jackson:
    default-property-inclusion: non_null

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
