server:
  port: 10086

logging:
  level:
    com.leslie.member: debug

spring:
  application:
    name: scorpio-member
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/scorpio_member?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: leslie
  redis:
    host: 192.168.174.100
    port: 6379
    password: leslie
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
