spring:
  cloud:
    gateway:
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*" # 允许哪些网站的跨域请求
#              - "http://localhost:8080"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期
      routes: # 网关路由配置
        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/user/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**
        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/search/**
        - id: collect-service
          uri: lb://collect-service
          predicates:
            - Path=/collect/**
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/admin/**
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/cart/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
        - id: fastdfs-service
          uri: lb://fastdfs-service
          predicates:
            - Path=/file/**
        - id: recommender-service
          uri: lb://recommender-service
          predicates:
              - Path=/recommender/**