spring:
  profiles:
    active: mq  # 激活mq配置
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
ribbon:
  eager-load:
    enabled: true #开启饥饿加载提升第一次访问速度
    clients:
      - product-service
feign:
  httpclient:
    enabled: true  # 开启httpClient接池
    max-connections: 200  #最大连接数量
    max-connections-per-route: 50  #单路径最大连接数
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 6000

elasticsearch-server-url: http://192.168.174.100:9200