spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/scorpio_cart?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: leslie
    type: com.alibaba.druid.pool.DruidDataSource

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

ribbon:
  eager-load:
    enabled: true
    clients:
      - product-service
feign:
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
