spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/scorpio_product?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: leslie
    type: com.alibaba.druid.pool.DruidDataSource
  profiles:
    active: mq  # 激活mq配置

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

ribbon:
  eager-load:
    enabled: true
    clients:
      - fastdfs-service
feign:
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
